Document how to turn the home page back on
jupyterhub/tmpauthenticator pull request #41
Opened 2023-04-27 15:55 UTC by yuvipanda

Since auto_login and login_service are configurable traitlets from the base class, we have only been setting the default here - it does not prevent them from being set in config.

Fixes https://github.com/jupyterhub/tmpauthenticator/issues/40

2023-04-27 20:03 UTC, consideRatio requested changes
I pushed a commit making `auto_login` configurable via traitlets and I'm trying to get configuring `login_service` via traitlets to work, but hasn't managed so far.

Note that without the pushed commit, the result is:

```
[W 2023-04-27 22:00:39.422 JupyterHub configurable:200] Config option `auto_login` not recognized by `TmpAuthenticator`.
```

Because `auto_login` the string can't be configured via traitlets, only `auto_login` the Boolean traitlets can be!

2023-04-27 20:39 UTC, consideRatio commented
@yuvipanda okay it appears that `login_service` the Unicode configurable traitlet wasn't marked with `.tag(config=True)`, so that made it not configurable via `c.ClassName.trait_name`.

I redefined it to be that. Now, what you documented works!

2023-04-27 20:41 UTC, consideRatio approved these changes
@yuvipanda wdyt?

2023-04-28 17:11 UTC, yuvipanda commented on tmpauthenticator/__init__.py
> +    login_service = Unicode(
Let's tag this as a configurable upstream as well?

2023-04-28 17:11 UTC, merged

2023-04-28 17:11 UTC, yuvipanda commented
@consideRatio one comment about making the login_service be configurable upstream as well, but otherwise lgtm.